// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.24;

import {IGroth16Verifier} from "../interfaces/IGroth16Verifier.sol";

// ILALVerifier is auto-generated by:
//   snarkjs zkey export solidityverifier build/ilal.zkey ILALVerifier.sol
// and placed in this directory after running circuits/scripts/compile.sh.
// It uses a fixed-size public signals array: uint[6] (6 public inputs in the circuit).
interface IILALVerifier {
    function verifyProof(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256[6] calldata _pubSignals
    ) external view returns (bool);
}

/// @title Groth16VerifierAdapter
/// @notice Wraps the snarkjs-generated ILALVerifier (fixed uint[6] pubSignals)
///         to satisfy IGroth16Verifier (dynamic uint[] pubSignals).
///         Deploy after running circuits/scripts/compile.sh, then queue and
///         activate it through CNFIssuer.proposeZKVerifier / activateZKVerifier.
contract Groth16VerifierAdapter is IGroth16Verifier {
    IILALVerifier public immutable verifier;

    // Number of public signals in the ILAL circuit (must match IILALVerifier above)
    uint256 private constant N_PUB = 6;

    constructor(address _verifier) {
        verifier = IILALVerifier(_verifier);
    }

    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[] calldata publicInputs
    ) external view override returns (bool) {
        require(publicInputs.length == N_PUB, "Adapter: wrong pubSignals length");

        uint256[N_PUB] memory pub;
        for (uint256 i = 0; i < N_PUB; i++) {
            pub[i] = publicInputs[i];
        }

        return verifier.verifyProof(a, b, c, pub);
    }
}
