import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {existsSync,mkdirSync,readFileSync,renameSync,writeFileSync} from 'node:fs';
import {dirname} from 'node:path';
import * as sdk from '../../sdk/dist/index.js';
import {checkpoint,normalized,pinned,stateAt} from './evidence-v2.mjs';
import {FORMAT,verifyZkEvidence} from './zk-evidence.mjs';
const require=createRequire(new URL('../../sdk/package.json',import.meta.url));
const {encodeAbiParameters,encodeFunctionData,keccak256,parseAbi,toHex}=require('viem');
const tokenAbi=parseAbi(['function mint(address,uint256)','function approve(address,uint256) returns(bool)']);
const zero=toHex(0n,{size:32});

/** Resumable ZK_ONLY lifecycle. Signed raw transactions are journaled before broadcast. */
export async function lifecycleZk({client,wallets,manifest,proofBundle,journalPath,outputPath}){
 const d=manifest,roles=d.pilot.roles,assets=d.pilot.assets;
 const save=()=>{mkdirSync(dirname(journalPath),{recursive:true});writeFileSync(`${journalPath}.tmp`,sdk.mixedJSON(journal)+'\n',{mode:0o600});renameSync(`${journalPath}.tmp`,journalPath);};
 const identity=keccak256(new TextEncoder().encode(sdk.mixedJSON({chainId:d.chainId,contracts:d.contracts,roles,root:proofBundle.metadata.acceptedRoot})));
 const journal=existsSync(journalPath)?JSON.parse(readFileSync(journalPath,'utf8')):{identity,serial:0,steps:{},evidence:{format:FORMAT,status:'INCOMPLETE',chainId:d.chainId,roles,assets,deployment:d,proofBundle,cases:{},grants:{},transactions:{},lp:{userSalt:zero,tickLower:-1000,tickUpper:1000}}};
 assert.equal(journal.identity,identity,'Journal deployment identity');const e=journal.evidence;
 for(const [role,address] of Object.entries(roles))assert.equal(wallets[role].account.address.toLowerCase(),address.toLowerCase());
 const fresh=()=>{journal.serial++;save();return toHex(BigInt(journal.serial),{size:32});};
 async function send(label,role,address,abi,fn,args,expected='success'){
  const data=encodeFunctionData({abi,functionName:fn,args}),wallet=wallets[role];let step=journal.steps[label];
  if(!step){const request=await wallet.prepareTransactionRequest({account:wallet.account,to:address,data,value:0n,gas:expected==='reverted'?2000000n:undefined});const serialized=await wallet.signTransaction(request);step=journal.steps[label]={serialized,hash:keccak256(serialized),from:roles[role],to:address,data,expected};save();}
  assert.equal(step.data,data,`Resume calldata mismatch: ${label}`);let receipt;try{receipt=await client.getTransactionReceipt({hash:step.hash});}catch(error){if(error.name!=='TransactionReceiptNotFoundError')throw error;}
  if(!receipt){try{await client.sendRawTransaction({serializedTransaction:step.serialized});}catch(error){try{await client.getTransaction({hash:step.hash});}catch{throw error;}}receipt=await client.waitForTransactionReceipt({hash:step.hash,timeout:120000});}
  assert.equal(receipt.status,expected,`Unexpected receipt: ${label}`);const block=await checkpoint(client,receipt.blockNumber);step.block=block;save();return {hash:step.hash,from:step.from,to:step.to,data:step.data,block};
 }
 async function once(key,fn){if(!(key in journal)){journal[key]=normalized(await fn());save();}return journal[key];}
 const initial=await sdk.readMixedPolicy(client,d);assert.equal(initial.config.mode,2);assert.equal(String(initial.config.acceptedRoot),String(proofBundle.metadata.acceptedRoot));
 for(const [label,role,asset,user,value] of [['mintALp','issuer','issuerStablecoin','liquidityProvider',1000000000000000n],['mintA','issuer','issuerStablecoin','institutionA',1000000000000n],['mintBLp','settlementAssetOperator','settlementCash','liquidityProvider',1000000000000000n],['mintB','settlementAssetOperator','settlementCash','institutionB',1000000000000n]])e.transactions[label]=await send(label,role,assets[asset].address,tokenAbi,'mint',[roles[user],value]);
 for(const [role,asset,router] of [['liquidityProvider','issuerStablecoin','liquidityRouter'],['liquidityProvider','settlementCash','liquidityRouter'],['institutionA','issuerStablecoin','executionRouter'],['institutionB','settlementCash','executionRouter']]){const label=`approve-${role}-${asset}`;e.transactions[label]=await send(label,role,assets[asset].address,tokenAbi,'approve',[d.contracts[router],(1n<<256n)-1n]);}
 async function grant(role){const proof=proofBundle.proofs.find(row=>row.role===role);assert(proof&&proof.wallet.toLowerCase()===roles[role].toLowerCase());const cached=await once(`grant-${role}`,async()=>{const p=await sdk.readMixedPolicy(client,d),b=await client.getBlock(),inputs=proof.inputs.map(BigInt);const activation={user:roles[role],poolId:d.pool.poolId,executionPolicyHash:p.executionPolicyHash,policyRevision:p.revision,source:2,acceptedRoot:p.config.acceptedRoot,rootEpoch:p.rootEpoch,evidenceHash:keccak256(encodeAbiParameters([{type:'bytes'},{type:'uint256[]'}],[proof.proof,inputs])),deadline:b.timestamp+1800n,nonce:fresh()};const signature=await wallets[role].signTypedData({account:wallets[role].account,domain:sdk.mixedDomain(d.chainId,d.contracts.grantManager,true),types:{MixedActivation:sdk.MixedActivationFields},primaryType:'MixedActivation',message:activation});return {activation,signature,proof:proof.proof,inputs};});e.transactions[`grant-${role}`]=await send(`grant-${role}`,role,d.contracts.grantManager,sdk.MixedGrantManagerAbi,'activate',[cached.activation,cached.signature,cached.proof,cached.inputs.map(BigInt)]);e.grants[role]={...cached,transaction:e.transactions[`grant-${role}`]};save();}
 for(const role of ['liquidityProvider','institutionA','institutionB'])await grant(role);
 async function lp(name,action,delta){const cached=await once(`lp-${name}`,async()=>{const p=await sdk.readMixedPolicy(client,d),b=await client.getBlock();const authorization={user:roles.liquidityProvider,poolId:d.pool.poolId,executionPolicyHash:p.executionPolicyHash,policyRevision:p.revision,action,tickLower:-1000,tickUpper:1000,liquidityDelta:delta,userSalt:zero,amount0Limit:action===3?(1n<<127n)-1n:0n,amount1Limit:action===3?(1n<<127n)-1n:0n,deadline:b.timestamp+1800n,nonce:fresh()};const signature=await wallets.liquidityProvider.signTypedData({account:wallets.liquidityProvider.account,domain:sdk.mixedDomain(d.chainId,d.contracts.hook),types:{MixedLiquidity:sdk.MixedLiquidityFields},primaryType:'MixedLiquidity',message:authorization});return {authorization,signature};});const tx=await send(`lp-${name}`,'liquidityProvider',d.contracts.liquidityRouter,sdk.MixedLiquidityRouterAbi,'modify',[d.pool,cached.authorization,cached.signature]);const before=await checkpoint(client,BigInt(tx.block.blockNumber)-1n);e.lp[name]={...cached,transaction:tx,before,after:tx.block,stateBefore:await stateAt(client,e,before),stateAfter:await stateAt(client,e,tx.block)};save();}
 await lp('add',3,100000000000000n);
 async function quote(name){return once(`case-${name}`,async()=>{const p=await sdk.readMixedPolicy(client,d),b=await client.getBlock(),a0=assets.issuerStablecoin.address.toLowerCase()===d.pool.currency0.toLowerCase();const orders=['institutionA','institutionB'].map((role,i)=>({user:roles[role],poolId:d.pool.poolId,executionPolicyHash:p.executionPolicyHash,policyRevision:p.revision,zeroForOne:i===0?a0:!a0,amountIn:i===0?100000000n:70000000n,minAmountOut:0n,maxAmmInput:i===0?100000000n:70000000n,minSqrtPriceX96:sdk.MIN_SQRT,maxSqrtPriceX96:sdk.MAX_SQRT,deadline:b.timestamp+1800n,nonce:fresh()}));return {quote:await sdk.quoteMixedOrders(pinned(client,b.number),d,orders),signed:await Promise.all(orders.map((order,i)=>sdk.signMixedOrder(wallets[i===0?'institutionA':'institutionB'],d,order))) };});}
 async function execute(name,expected){const scenario=await quote(name),files=scenario.signed.map(sdk.parseSignedMixedOrder),orders=files.map(x=>x.order),tx=await send(`execute-${name}`,'executor',d.contracts.executionRouter,sdk.MixedExecutionRouterAbi,'executeBatch',[d.pool,orders,files.map(x=>x.signature)],expected),before=await checkpoint(client,BigInt(tx.block.blockNumber)-1n);e.cases[name]={...scenario,transaction:tx,before,after:tx.block,stateBefore:await stateAt(client,e,before,orders),stateAfter:await stateAt(client,e,tx.block,orders)};save();}
 await execute('execution','success');await quote('rootRetirement');e.transactions.invalidateRoot=await send('invalidateRoot','issuer',d.contracts.policyRegistry,sdk.MixedPolicyRegistryAbi,'invalidateRoot',[d.pool.poolId]);save();await execute('rootRetirement','reverted');
 await lp('collect',5,0n);await lp('exit',4,-100000000000000n);
 e.snapshot=await checkpoint(client,BigInt(e.lp.exit.after.blockNumber));e.flow={grossInstitutionalFlow:'170000000',internallyMatchedFlow:'140000000',actualAmmInput:'30000000'};e.status='COMPLETE';save();
 const result=await verifyZkEvidence(client,e);mkdirSync(dirname(outputPath),{recursive:true});writeFileSync(outputPath,sdk.mixedJSON(e)+'\n');return result;
}
