import { Command } from 'commander';
import { readFileSync,writeFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { createPublicClient,defineChain,http,getAddress,encodeAbiParameters,encodeFunctionData,keccak256,erc20Abi,type Address,type Hex,type PublicClient } from 'viem';
import { checkMixedDeployment,validateMixedDeployment,parseMixedOrder,parseSignedMixedOrder,readMixedPolicy,quoteMixedOrders,signMixedOrder,executeMixedOrders,activateMixedGrant,modifyMixedLiquidity,cancelMixedNonce,mixedJSON,readMixedMarket,readMixedOrderStatus,MixedHookAbi,MixedGrantManagerAbi,MixedPolicyRegistryAbi,MixedExecutionRouterAbi,MixedOracleGuardAbi,type MixedDeployment,type MixedActivation,type MixedLiquidity } from '@ilalv3/sdk';
import { createExecutionClients } from '../signer.js';
import { buildMixedIssuer,type MixedIssuerInput } from '../mixedIssuer.js';
import { startMixedConsole } from './mixedConsole.js';
export const readMixedJSON=(file:string)=>JSON.parse(readFileSync(file,'utf8'));
export function mixedContext(manifest:string,rpc:string) {
 const deployment=readMixedJSON(manifest) as MixedDeployment;validateMixedDeployment(deployment);
 const chain=defineChain({id:deployment.chainId,name:`ILAL Mixed ${deployment.chainId}`,nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:{default:{http:[rpc]}},testnet:deployment.classification!=='production'});
 return {deployment,chain,client:createPublicClient({chain,transport:http(rpc)}) as PublicClient};
}
const output=(v:unknown,path?:string)=>{const s=mixedJSON(v);if(path)writeFileSync(path,s+'\n',{mode:0o600});else console.log(s);};
export function activationFromPolicy(user:Address,d:MixedDeployment,p:Awaited<ReturnType<typeof readMixedPolicy>>,source:number,proof:Hex,inputs:bigint[],now:bigint):MixedActivation {
 return {user,poolId:d.pool.poolId,executionPolicyHash:p.executionPolicyHash,policyRevision:p.revision,source,acceptedRoot:p.config.acceptedRoot,rootEpoch:p.rootEpoch,evidenceHash:keccak256(encodeAbiParameters([{type:'bytes'},{type:'uint256[]'}],[proof,inputs])),deadline:now+600n,nonce:`0x${randomBytes(32).toString('hex')}`};
}
export async function monitorMixed(client:PublicClient,d:MixedDeployment,user?:Address,fromBlock?:bigint) {
 await checkMixedDeployment(client,d);const block=await client.getBlock(),policy=await readMixedPolicy(client,d,block.number);
 const logs=await client.getLogs({address:[d.contracts.hook,d.contracts.policyRegistry,d.contracts.grantManager,d.contracts.executionRouter],fromBlock:fromBlock??block.number,toBlock:block.number});
 const grant=user?await client.readContract({address:d.contracts.grantManager,abi:MixedGrantManagerAbi,functionName:'grants',args:[d.pool.poolId,user],blockNumber:block.number}):null;
 const eligible=user?await client.readContract({address:d.contracts.grantManager,abi:MixedGrantManagerAbi,functionName:'isEligible',args:[d.pool.poolId,user,policy.executionPolicyHash,policy.revision],blockNumber:block.number}):null;
 const market=await readMixedMarket(client,d,block.number);
 return {market,format:'ilal-mixed-monitor-v1',snapshot:{blockNumber:block.number,blockHash:block.hash},policy,user,grant,eligible,logs,note:'Read-only snapshot. Reverted transactions emit no logs; query submitted receipts separately.'};
}
export function registerMixed(program:Command) {
 const mixed=program.command('mixed').description('Versioned Mixed execution, policy grants and owner-isolated LP');
 const common=(name:string,description:string)=>mixed.command(name).description(description).requiredOption('--manifest <path>','Mixed deployment manifest').requiredOption('--rpc <url>','Explicit RPC URL').option('-o, --output <path>','Write JSON result');
 common('check','Check chain, code and immutable deployment bindings').action(async o=>{const c=mixedContext(o.manifest,o.rpc);output(await checkMixedDeployment(c.client,c.deployment),o.output);});
 common('monitor','Read policy, eligibility and recent logs; never sends notifications').option('--user <address>').option('--from-block <number>').action(async o=>{const c=mixedContext(o.manifest,o.rpc);output(await monitorMixed(c.client,c.deployment,o.user?getAddress(o.user):undefined,o.fromBlock?BigInt(o.fromBlock):undefined),o.output);});
 common('status','Read a signed order nonce, deadline and current eligibility').requiredOption('--input <path>').action(async o=>{const c=mixedContext(o.manifest,o.rpc);output(await readMixedOrderStatus(c.client,c.deployment,parseSignedMixedOrder(readMixedJSON(o.input))),o.output);});
 common('quote','Full forced-revert settlement simulation of unsigned orders').requiredOption('--input <path>','JSON array of unsigned orders').option('--direct','One explicit direct swap',false).action(async o=>{const c=mixedContext(o.manifest,o.rpc);const raw=readMixedJSON(o.input);if(!Array.isArray(raw))throw new Error('Expected order array');output(await quoteMixedOrders(c.client,c.deployment,raw.map(parseMixedOrder),o.direct),o.output);});
 common('sign','Sign a versioned order; does not grant token allowance').requiredOption('--input <path>','Unsigned order JSON').option('--direct','Sign DIRECT_SWAP instead of BATCH_ORDER',false).action(async o=>{const c=mixedContext(o.manifest,o.rpc);await checkMixedDeployment(c.client,c.deployment);const signer=await createExecutionClients({chain:c.chain,rpc:o.rpc});output(await signMixedOrder(signer.walletClient,c.deployment,parseMixedOrder(readMixedJSON(o.input)),o.direct),o.output);});
 common('execute','Re-simulate signed batch/direct orders then execute atomically').requiredOption('--input <path>','Array of signed Mixed order files').action(async o=>{const c=mixedContext(o.manifest,o.rpc);const raw=readMixedJSON(o.input);if(!Array.isArray(raw))throw new Error('Expected signed order array');const signer=await createExecutionClients({chain:c.chain,rpc:o.rpc});output(await executeMixedOrders(c.client,signer.walletClient,c.deployment,raw.map(parseSignedMixedOrder)),o.output);});
 common('cancel','Cancel only the selected nonce namespace; receipt is authoritative').requiredOption('--namespace <0-5>').requiredOption('--nonce <bytes32>').action(async o=>{const c=mixedContext(o.manifest,o.rpc);await checkMixedDeployment(c.client,c.deployment);const signer=await createExecutionClients({chain:c.chain,rpc:o.rpc});const hash=await cancelMixedNonce(c.client,signer.walletClient,c.deployment,Number(o.namespace),o.nonce as Hex);output(await confirmed(c.client,hash),o.output);});
 common('grant','Activate the explicitly selected CNF=1 / ZK=2 / BOTH=3 source').requiredOption('--source <1-3>').option('--proof <path>','JSON {proof: ABI-encoded hex, inputs: decimal strings[]}').action(async o=>{const c=mixedContext(o.manifest,o.rpc);const signer=await createExecutionClients({chain:c.chain,rpc:o.rpc});const raw=o.proof?readMixedJSON(o.proof):{proof:'0x',inputs:[]};const proof=raw.proof as Hex,inputs=raw.inputs.map(BigInt) as bigint[];const p=await readMixedPolicy(c.client,c.deployment),block=await c.client.getBlock();const a=activationFromPolicy(signer.address,c.deployment,p,Number(o.source),proof,inputs,block.timestamp);output(await confirmed(c.client,await activateMixedGrant(c.client,signer.walletClient,c.deployment,a,proof,inputs)),o.output);});
 common('liquidity','ADD=3 / EXIT=4 / COLLECT=5; exits never require a current grant').requiredOption('--input <path>','Liquidity authorization JSON').action(async o=>{const c=mixedContext(o.manifest,o.rpc);const signer=await createExecutionClients({chain:c.chain,rpc:o.rpc});const a=parseLiquidity(readMixedJSON(o.input));output(await confirmed(c.client,await modifyMixedLiquidity(c.client,signer.walletClient,c.deployment,a)),o.output);});
 common('approve','Explicit ERC-20 spending approval, separate from order signing').requiredOption('--token <address>').requiredOption('--amount <raw>').option('--liquidity','Approve canonical LP Router instead',false).action(async o=>{const c=mixedContext(o.manifest,o.rpc);await checkMixedDeployment(c.client,c.deployment);const token=getAddress(o.token);if(![c.deployment.pool.currency0,c.deployment.pool.currency1].some(t=>t.toLowerCase()===token.toLowerCase()))throw new Error('Unsupported asset');const amount=BigInt(o.amount);if(amount<0n)throw new Error('Amount');const signer=await createExecutionClients({chain:c.chain,rpc:o.rpc});const spender=o.liquidity?c.deployment.contracts.liquidityRouter:c.deployment.contracts.executionRouter;const {request}=await c.client.simulateContract({address:token,abi:erc20Abi,functionName:'approve',args:[spender,amount],account:signer.account});output(await confirmed(c.client,await signer.walletClient.writeContract({...request,account:signer.account,chain:c.chain})),o.output);});
 common('policy-prepare','Produce reviewable governance calldata; never broadcasts').requiredOption('--action <name>','configure,activate,disable,invalidateRoot,ban,proposeUnban,activateUnban,cancelProposal').option('--input <path>','Config JSON for configure').option('--user <address>').action(async o=>{const c=mixedContext(o.manifest,o.rpc);await checkMixedDeployment(c.client,c.deployment);const id=c.deployment.pool.poolId;let data:Hex;
  if(o.action==='configure'){const x=readMixedJSON(o.input);const config={...x,issuerHash:BigInt(x.issuerHash),schemaHash:BigInt(x.schemaHash),acceptedRoot:BigInt(x.acceptedRoot),jurisdictionRoot:BigInt(x.jurisdictionRoot),zkPolicyHash:BigInt(x.zkPolicyHash),maxGrantTTL:BigInt(x.maxGrantTTL)};data=encodeFunctionData({abi:MixedPolicyRegistryAbi,functionName:'configure',args:[id,config]});}
  else if(['ban','proposeUnban','activateUnban'].includes(o.action)){data=encodeFunctionData({abi:MixedPolicyRegistryAbi,functionName:o.action as 'ban'|'proposeUnban'|'activateUnban',args:[id,getAddress(o.user)]});}
  else if(['activate','disable','invalidateRoot','cancelProposal'].includes(o.action)){data=encodeFunctionData({abi:MixedPolicyRegistryAbi,functionName:o.action as 'activate'|'disable'|'invalidateRoot'|'cancelProposal',args:[id]});}
  else throw new Error('Unknown governance action');output({chainId:c.deployment.chainId,to:c.deployment.contracts.policyRegistry,value:'0',data,note:'Submit via configured admin/Safe. Changes and re-enablement require on-chain delay.'},o.output);});
 mixed.command('issuer-build').description('Build issuer-controlled policy tree and private witnesses').requiredOption('--input <path>').requiredOption('--output <directory>').action(o=>output(buildMixedIssuer(readMixedJSON(o.input) as MixedIssuerInput,o.output)));
 mixed.command('console').description('Local Mixed browser application; all signing stays in wallet').requiredOption('--manifest <path>').requiredOption('--rpc <url>').option('--port <number>','Loopback port','4174').action(async o=>{await startMixedConsole(o);});
}
export function parseLiquidity(x:Record<string,unknown>):MixedLiquidity {return {...x,user:getAddress(String(x.user)),poolId:x.poolId as Hex,executionPolicyHash:x.executionPolicyHash as Hex,policyRevision:BigInt(String(x.policyRevision)),action:Number(x.action),tickLower:Number(x.tickLower),tickUpper:Number(x.tickUpper),liquidityDelta:BigInt(String(x.liquidityDelta)),userSalt:x.userSalt as Hex,amount0Limit:BigInt(String(x.amount0Limit)),amount1Limit:BigInt(String(x.amount1Limit)),deadline:BigInt(String(x.deadline)),nonce:x.nonce as Hex};}
export async function confirmed(client:PublicClient,hash:Hex){const receipt=await client.waitForTransactionReceipt({hash});if(receipt.status!=='success')throw new Error(`Transaction reverted: ${hash}`);return receipt;}
