/** Verify the public, non-secret evidence needed for ceremony and real-issuer diligence. */
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
const HASH=/^[0-9a-f]{64}$/;
const ADDRESS=/^0x[0-9a-fA-F]{40}$/;
const hashFile=path=>createHash('sha256').update(readFileSync(path)).digest('hex');
const json=path=>JSON.parse(readFileSync(path,'utf8'));
const hash=(value,name)=>assert.match(value??'',HASH,`${name} must be a lowercase SHA-256 digest`);

export function verifyFreeze(manifest,root=process.cwd()){
 assert.equal(manifest.format,'ilal-circuit-freeze-v1');assert.equal(manifest.status,'FROZEN');assert.equal(manifest.circuit.name,'ILALEligibilityPolicyV2');assert.equal(manifest.circuit.version,2);assert.equal(manifest.circuit.publicInputs,9);assert.deepEqual(manifest.circuit.publicSignalOrder,['walletHash','issuerHash','schemaHash','expiresAt','credentialRoot','minKycLevel','jurisdictionRoot','policyHash','circuitVersion']);
 assert(manifest.sources.length>=6);for(const row of manifest.sources){hash(row.sha256,`source ${row.path}`);assert.equal(hashFile(resolve(root,row.path)),row.sha256,`Frozen source changed: ${row.path}`);}
 hash(manifest.sourceSetSHA256,'sourceSetSHA256');const digest=createHash('sha256');for(const row of [...manifest.sources].sort((a,b)=>a.path.localeCompare(b.path))){digest.update(row.path);digest.update('\0');digest.update(row.sha256);digest.update('\n');}assert.equal(digest.digest('hex'),manifest.sourceSetSHA256,'Source-set digest');
 assert.equal(manifest.changeControl.requiresNewCircuitVersion,true);assert.equal(manifest.changeControl.productionCeremonyMayNotModifySources,true);return {status:'VERIFIED',sourceSetSHA256:manifest.sourceSetSHA256};
}

export function verifyCeremony(manifest,{root=process.cwd(),requireComplete=false,freeze}={}){
 assert.equal(manifest.format,'ilal-independent-ceremony-v1');assert(['DRAFT','COMPLETE'].includes(manifest.status));if(requireComplete)assert.equal(manifest.status,'COMPLETE','Ceremony is not complete');
 assert.equal(manifest.circuitSourceSetSHA256,freeze.sourceSetSHA256);assert.equal(manifest.circuitVersion,2);assert.equal(manifest.ceremonyType,'Groth16 phase 2');assert.equal(manifest.projectControlExcluded,true);
 if(manifest.status==='DRAFT')return {status:'DRAFT_VALID'};
 const entities=[manifest.coordinator.entityId,manifest.independentVerifier.entityId,...manifest.contributions.map(x=>x.entityId)];assert.equal(new Set(entities).size,entities.length,'Coordinator, verifier and contributors must be independent entities');const organizations=[manifest.coordinator.organizationReference,manifest.independentVerifier.organizationReference,...manifest.contributions.map(x=>x.organizationReference)];assert.equal(new Set(organizations).size,organizations.length,'Ceremony roles must belong to distinct organizations');assert(manifest.contributions.length>=2,'At least two independent contributions required');
 for(const [name,row] of [['coordinator',manifest.coordinator],['independentVerifier',manifest.independentVerifier]]){assert(row.entityId&&row.organizationReference);hash(row.attestationSHA256,`${name} attestation`);}
 for(const key of ['ptauSHA256','initialZkeySHA256','r1csSHA256'])hash(manifest.phase2[key],`phase2.${key}`);assert.equal(manifest.phase2.r1csSHA256,freeze.developmentReferenceArtifacts.r1csSHA256,'Ceremony R1CS must match frozen circuit');let prior=manifest.phase2.initialZkeySHA256;
 for(let i=0;i<manifest.contributions.length;i++){const row=manifest.contributions[i];assert(row.entityId&&row.organizationReference,`Contribution ${i+1} identity`);assert.equal(row.sequence,i+1);assert.equal(row.inputZkeySHA256,prior,`Contribution ${i+1} input chain`);for(const key of ['inputZkeySHA256','outputZkeySHA256','challengeSHA256','responseSHA256','verificationLogSHA256','attestationSHA256'])hash(row[key],`contribution ${i+1}.${key}`);prior=row.outputZkeySHA256;}
 assert.equal(manifest.beacon.inputZkeySHA256,prior);for(const key of ['inputZkeySHA256','outputZkeySHA256','publicEntropySHA256','verificationLogSHA256'])hash(manifest.beacon[key],`beacon.${key}`);assert(manifest.beacon.publicSource&&manifest.beacon.appliedAt);
 assert.equal(manifest.artifacts.zkeySHA256,manifest.beacon.outputZkeySHA256);for(const key of ['zkey','vkey','solidityVerifierSource']){const row=manifest.artifacts[key];hash(row.sha256,`artifact ${key}`);assert.equal(hashFile(resolve(root,row.path)),row.sha256,`Artifact changed: ${key}`);}assert.equal(manifest.artifacts.zkeySHA256,manifest.artifacts.zkey.sha256);assert.equal(manifest.artifacts.vkeySHA256,manifest.artifacts.vkey.sha256);hash(manifest.artifacts.verifierRuntimeCodeHash.replace(/^0x/,''),'verifierRuntimeCodeHash');
 assert.equal(manifest.verification.ptauVerified,true);assert.equal(manifest.verification.r1csMatched,true);assert.equal(manifest.verification.finalZkeyVerified,true);hash(manifest.verification.transcriptSHA256,'verification transcript');assert(manifest.verification.verifiedAt);return {status:'VERIFIED',zkeySHA256:manifest.artifacts.zkeySHA256,vkeySHA256:manifest.artifacts.vkeySHA256,transcriptSHA256:manifest.verification.transcriptSHA256};
}

export function verifyIssuerAcceptance(manifest,{requireComplete=false,ceremony}={}){
 assert.equal(manifest.format,'ilal-real-issuer-pilot-acceptance-v1');assert(['DRAFT','ACCEPTED','COMPLETE'].includes(manifest.status));if(requireComplete)assert(['ACCEPTED','COMPLETE'].includes(manifest.status),'Issuer acceptance is not signed');
 assert.equal(manifest.lifecycle,'ilal-zk-issuer-pilot-evidence-v1');assert.equal(manifest.assetA.synthetic,false);assert.equal(manifest.assetA.issuerControlsIssuance,true);assert.equal(manifest.assetA.protocolExternalTransferBoundaryAcknowledged,true);assert.equal(manifest.responsibility.issuerDefinesEligibility,true);assert.equal(manifest.responsibility.issuerOwnsIdentityProviderRelationship,true);assert.equal(manifest.responsibility.ilalMakesRegulatoryDecisions,false);assert.equal(manifest.responsibility.ilalCustodiesAssets,false);assert.equal(manifest.responsibility.ilalControlsExternalAssetTransfers,false);
 if(manifest.status==='DRAFT')return {status:'DRAFT_VALID'};
 assert.equal(manifest.settlementAsset.issuerApproved,true);assert.match(manifest.settlementAsset.contractAddress??'',ADDRESS,'settlement asset contract');assert(manifest.issuer.organizationReference&&manifest.issuer.jurisdiction);hash(manifest.issuer.legalIdentityEvidenceSHA256,'issuer legal identity');hash(manifest.issuer.authorizedSignerAttestationSHA256,'issuer signer attestation');assert.match(manifest.assetA.contractAddress,ADDRESS);assert(Number.isInteger(manifest.assetA.decimals));
 const roleNames=['issuer','assetAController','policyAdmin','liquidityProvider','institutionA','institutionB','executor'],roles=roleNames.map(name=>manifest.roles[name]);roles.forEach((address,name)=>assert.match(address??'',ADDRESS,`role ${roleNames[name]}`));assert.equal(new Set(roles.map(x=>x.toLowerCase())).size,roles.length,'Pilot roles must be distinct');assert.equal(manifest.responsibility.issuerControlsAssetA,true);assert.equal(manifest.responsibility.issuerControlsPolicy,true);hash(manifest.responsibility.assetAControlEvidenceSHA256,'Asset A control evidence');hash(manifest.responsibility.policyControlEvidenceSHA256,'policy control evidence');
 assert.equal(manifest.ceremony.zkeySHA256,ceremony.zkeySHA256);assert.equal(manifest.ceremony.vkeySHA256,ceremony.vkeySHA256);hash(manifest.ceremony.manifestSHA256,'ceremony manifest');for(const key of ['deploymentManifestSHA256','evidenceSHA256','issuerAcceptanceSHA256'])hash(manifest.acceptance[key],`acceptance.${key}`);for(const key of ['zkGrantsVerified','gross170Matched140Residual30','rootRetirementAtomicRollback','lpCollectedNonzeroFees','lpFullyExited','zeroTransientInventory','independentHistoricalVerification'])assert.equal(manifest.acceptance[key],true,`Missing acceptance: ${key}`);return {status:'VERIFIED',issuer:manifest.issuer.organizationReference,evidenceSHA256:manifest.acceptance.evidenceSHA256};
}

if(process.argv[1]===new URL(import.meta.url).pathname){const args=process.argv.slice(2),complete=args.includes('--require-complete'),paths=args.filter(x=>x!=='--require-complete');if(paths.length<1||paths.length>3)throw new Error('Usage: verify-package.mjs circuit-freeze.json [ceremony.json issuer-acceptance.json] [--require-complete]');const freezeManifest=json(paths[0]),freeze=verifyFreeze(freezeManifest);const result={freeze};if(paths[1]){const ceremonyManifest=json(paths[1]),ceremony=verifyCeremony(ceremonyManifest,{requireComplete:complete,freeze:freezeManifest});result.ceremony=ceremony;if(paths[2])result.issuer=verifyIssuerAcceptance(json(paths[2]),{requireComplete:complete,ceremony});}console.log(JSON.stringify(result,null,2));}
